// jessica_ffi.h — generated by cbindgen. DO NOT EDIT.

#ifndef JESSICA_FFI_H
#define JESSICA_FFI_H

#pragma once

#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

/**
 * Returned by FFI ops that need to signal a binary failure (instead
 * of a real outcome). Kept as separate constants so cbindgen emits
 * them as `#define`s — easier on Swift's importer.
 */
#define JESSICA_OK 0

#define JESSICA_ERR_BAD_HANDLE -1

#define JESSICA_ERR_BAD_UTF8 -2

#define JESSICA_ERR_BAD_INPUT -3

#define JESSICA_ERR_PANIC -99

/**
 * Status code returned by [`jessica_ffi_merge_fact`].
 *
 * Non-negative values are real outcomes; negative values are errors
 * (see `JESSICA_ERR_*` constants for the encoded reasons).
 */
enum JessicaMergeOutcome {
  /**
   * Fact stored fresh.
   */
  JESSICA_MERGE_OUTCOME_ACCEPTED = 0,
  /**
   * Identical fact already present — no-op.
   */
  JESSICA_MERGE_OUTCOME_DUPLICATE_NO_OP = 1,
  /**
   * Existing fact superseded by a newer one.
   */
  JESSICA_MERGE_OUTCOME_RESOLVED_NEWER = 2,
  /**
   * Local fact kept; incoming fact discarded.
   */
  JESSICA_MERGE_OUTCOME_RESOLVED_KEEP_LOCAL = 3,
};
typedef int32_t JessicaMergeOutcome;

#endif  /* JESSICA_FFI_H */
