[package]
name = "blazend-tts"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Piper TTS wrapper for blazen_os."

[[bin]]
name = "blazend-tts"
path = "src/main.rs"

[dependencies]
blazend-ipc        = { workspace = true }
blazend-audioring  = { path = "../blazend-audioring" }
tokio              = { workspace = true }
anyhow             = { workspace = true }
tracing            = { workspace = true }
tracing-subscriber = { workspace = true }
clap               = { workspace = true }
